packages:
  - "ast"
  - "parser"
  - "formatter"
  - "language-service"
  - "converters-ascii"
  - "converters-svg"
  - "converters-midi"
  - "converters-musicxml"
  - "converters-guitarpro"
  - "opentab"
